"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { DemoPreview } from "@/components/demo-preview";

export default function Home(){
 const[role,setRole]=useState<"student"|"staff">("student"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[authError,setAuthError]=useState(""),[authLoading,setAuthLoading]=useState(false);
 const[demo,setDemo]=useState<"student"|"checker"|"dean"|null>(null);
 async function routeUser(userId:string){const supabase=createClient();if(!supabase)return;const{data:profile,error}=await supabase.from("profiles").select("role").eq("id",userId).single();if(error||!profile)throw new Error("Your account profile is not ready. Contact a Dean.");window.location.assign(profile.role==="dean"?"/admin":profile.role==="checker"?"/checker":"/student")}
 async function signInWithEmail(event:FormEvent){event.preventDefault();const supabase=createClient();if(!supabase){setAuthError("Authentication is not configured yet.");return}setAuthLoading(true);setAuthError("");const{data,error}=await supabase.auth.signInWithPassword({email,password});if(error||!data.user){setAuthError(error?.message??"We could not sign you in.");setAuthLoading(false);return}try{await routeUser(data.user.id)}catch(cause){setAuthError(cause instanceof Error?cause.message:"Account access failed");setAuthLoading(false)}}
 async function signInWithGoogle(){const supabase=createClient();if(!supabase){setAuthError("Authentication is not configured yet.");return}setAuthError("");const{error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${window.location.origin}/auth/callback`}});if(error)setAuthError(error.message)}
 if(demo)return <DemoPreview role={demo} close={()=>setDemo(null)}/>;
 return <main className="login-page"><section className="login-brand"><div className="login-seal">K</div><span>KINGSWAY COLLEGE</span><h1>Every student.<br/>Safely accounted for.</h1><p>A secure, simple way to complete residence room checks — with real-time verification and clear accountability.</p><div className="trust"><ShieldCheck/><div><strong>Built for student safety</strong><small>Private records · Role-based access · Complete audit trail</small></div></div></section><section className="login-panel"><form className="login-card" onSubmit={signInWithEmail}><div className="mobile-brand"><span className="crest">K</span><strong>Kingsway Room Check</strong></div><h2>Welcome back</h2><p>Sign in to continue to Room Check.</p><div className="role-tabs"><button type="button" className={role==="student"?"active":""} onClick={()=>setRole("student")}>Student</button><button type="button" className={role==="staff"?"active":""} onClick={()=>setRole("staff")}>Staff & Dean</button></div><button type="button" className="google-btn" onClick={signInWithGoogle}><b>G</b>Continue with Google</button><div className="or"><span/>or use your email<span/></div><label className="form-label">Email address<div className="input-wrap"><Mail size={18}/><input required autoComplete="email" type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder={role==="student"?"student@kingsway.college":"staff@kingsway.college"}/></div></label><label className="form-label">Password<div className="input-wrap"><LockKeyhole size={18}/><input required autoComplete="current-password" type="password" value={password} onChange={event=>setPassword(event.target.value)} placeholder="Enter your password"/></div></label><div className="forgot"><span/><Link href="/forgot-password">Forgot password?</Link></div>{authError&&<p className="auth-error">{authError}</p>}<button className="sign-in" disabled={authLoading}>{authLoading?"Signing in…":"Sign in"}</button>{role==="student"&&<p className="register-prompt">New student? <Link href="/register">Create your account</Link></p>}<div className="demo-access"><span>Preview the complete system</span><div><button type="button" onClick={()=>setDemo("student")}>Student demo</button><button type="button" onClick={()=>setDemo("checker")}>Checker demo</button><button type="button" onClick={()=>setDemo("dean")}>Dean demo</button></div></div><small className="privacy">By continuing, you agree to the school&apos;s Acceptable Use and Privacy policies.</small></form></section></main>
}
