"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { Camera, Check, ClipboardCheck, DoorOpen, LoaderCircle, LogOut, RefreshCw, ScanLine, X } from "lucide-react";
import { authFetch } from "@/lib/auth-fetch";
import { ResidenceRequests } from "@/components/residence-requests";

type Room={id:string;room_number:string;capacity:number;floor_id:string;floors:{hall:string;floor_number:number;label:string}|null};
type Assignment={id:string;room_id:string;student_id:string;profiles:{id:string;full_name:string;student_code:string}|null};
type Event={id:string;scheduled_for:string;check_templates:{name:string;check_time:string}|null};
type Verification={id:string;event_id:string;student_id:string;room_id:string;method:string;status:string;verified_at:string};
type Data={rooms:Room[];assignments:Assignment[];event:Event|null;verifications:Verification[]};

export function CheckerLive({onLogout}:{onLogout:()=>Promise<void>}){
 const[data,setData]=useState<Data>({rooms:[],assignments:[],event:null,verifications:[]});const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[scanRoom,setScanRoom]=useState<Room|null>(null);const[photoTarget,setPhotoTarget]=useState<{room:Room;assignment:Assignment}|null>(null);const[notice,setNotice]=useState("");
 const load=useCallback(async()=>{try{setData(await authFetch("/api/checker/bootstrap"));setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load assigned rooms")}finally{setLoading(false)}},[]);useEffect(()=>{queueMicrotask(load)},[load]);
 useEffect(()=>{const timer=setInterval(()=>{if(!scanRoom&&!photoTarget)void load()},30000);return()=>clearInterval(timer)},[load,scanRoom,photoTarget]);
 const verified=(studentId:string)=>data.event&&data.verifications.find(v=>v.event_id===data.event?.id&&v.student_id===studentId&&v.status==="verified");
 return <main className="checker-live"><header><div className="brand compact"><span className="crest">K</span><div><strong>Kingsway</strong><small>Checker</small></div></div><div><a href="/student">My student QR</a><button title="Refresh rooms" onClick={load}><RefreshCw/></button><button onClick={onLogout}><LogOut/></button></div></header>{loading?<div className="live-loading"><LoaderCircle/><p>Loading your assigned floor…</p></div>:<><section className="checker-live-head"><div><span>{data.event?"ROOM CHECK IN PROGRESS":"NO OPEN SESSION"}</span><h1>{data.event?.check_templates?.name||"Room check unavailable"}</h1><p>{data.event?new Date(data.event.scheduled_for).toLocaleString():"A Dean must open a session before scanning."}</p></div><b>{data.verifications.filter(v=>v.event_id===data.event?.id&&v.status==="verified").length}<small> verified</small></b></section>{error&&<div className="live-alert error">{error}</div>}{notice&&<div className="live-alert success"><Check/>{notice}<button onClick={()=>setNotice("")}><X/></button></div>}<section className="checker-room-list">{data.rooms.map(room=>{const people=data.assignments.filter(a=>a.room_id===room.id);const done=people.filter(a=>verified(a.student_id)).length;return <article key={room.id}><header><div><DoorOpen/><div><span>{room.floors?.hall} · {room.floors?.label}</span><h2>Room {room.room_number}</h2></div></div><b>{done}/{people.length}</b></header>{people.map(assignment=>{const check=verified(assignment.student_id),pending=data.verifications.find(v=>v.event_id===data.event?.id&&v.student_id===assignment.student_id&&v.status==="photo_review");return <div className="checker-student" key={assignment.id}><span className={check?"done":""}>{check?<Check/>:assignment.profiles?.full_name.split(" ").map(n=>n[0]).join("")}</span><div><strong>{assignment.profiles?.full_name}</strong><small>{check?`Verified · ${new Date(check.verified_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}`:pending?"Photo awaiting Dean review":assignment.profiles?.student_code}</small></div>{!check&&!pending&&data.event&&<button onClick={()=>setPhotoTarget({room,assignment})}><Camera/> No phone</button>}</div>})}<button className="room-scan" disabled={!data.event||!people.length} onClick={()=>setScanRoom(room)}><ScanLine/> Scan QR for Room {room.room_number}</button></article>})}{!data.rooms.length&&<div className="empty-state"><ClipboardCheck/><h3>No rooms assigned</h3><p>Ask a Dean to assign this checker to a floor or room.</p></div>}</section><ResidenceRequests rooms={data.rooms}/></>}{scanRoom&&data.event&&<Scanner room={scanRoom} eventId={data.event.id} close={()=>setScanRoom(null)} success={async()=>{setNotice("Student verified successfully");setScanRoom(null);await load()}}/>}{photoTarget&&data.event&&<PhotoModal target={photoTarget} eventId={data.event.id} close={()=>setPhotoTarget(null)} success={async()=>{setNotice("Photo sent for Dean review");setPhotoTarget(null);await load()}}/>}</main>
}

function Scanner({room,eventId,close,success}:{room:Room;eventId:string;close:()=>void;success:()=>Promise<void>}){const[error,setError]=useState("");const locked=useRef(false);useEffect(()=>{let scanner:{start:(camera:{facingMode:string},config:{fps:number;qrbox:{width:number;height:number}},success:(text:string)=>void,error:()=>void)=>Promise<unknown>;stop:()=>Promise<unknown>}|null=null;let active=true;async function begin(){try{const{Html5Qrcode}=await import("html5-qrcode");if(!active)return;scanner=new Html5Qrcode("live-qr-reader");await scanner.start({facingMode:"environment"},{fps:10,qrbox:{width:240,height:240}},async text=>{if(locked.current)return;locked.current=true;try{await authFetch("/api/check/verify",{method:"POST",body:JSON.stringify({token:text,eventId,roomId:room.id})});await scanner?.stop();await success()}catch(e){setError(e instanceof Error?e.message:"QR could not be verified");locked.current=false}},()=>{})}catch(e){setError(e instanceof Error?e.message:"Camera could not be started")}}begin();return()=>{active=false;scanner?.stop().catch(()=>{})}},[eventId,room.id,success]);return <div className="modal-backdrop"><div className="scanner-live-modal"><header><div><span>SCANNING</span><h2>Room {room.room_number}</h2></div><button onClick={close}><X/></button></header><div id="live-qr-reader"/>{error&&<div className="live-alert error">{error}</div>}<p>Hold the student&apos;s rotating QR code inside the frame.</p></div></div>}

function PhotoModal({target,eventId,close,success}:{target:{room:Room;assignment:Assignment};eventId:string;close:()=>void;success:()=>Promise<void>}){const[file,setFile]=useState<File|null>(null);const[notes,setNotes]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function submit(){if(!file)return;setBusy(true);try{const form=new FormData();form.set("photo",file);form.set("eventId",eventId);form.set("roomId",target.room.id);form.set("studentId",target.assignment.student_id);form.set("notes",notes);await authFetch("/api/check/photo",{method:"POST",body:form});await success()}catch(e){setError(e instanceof Error?e.message:"Upload failed");setBusy(false)}}return <div className="modal-backdrop"><div className="photo-live-modal"><header><div><span>PHOTO EXCEPTION</span><h2>{target.assignment.profiles?.full_name}</h2></div><button onClick={close}><X/></button></header><label className="camera-input"><Camera/><strong>Take or choose a photo</strong><small>JPG, PNG or WebP · maximum 5 MB</small><input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>{file&&<p className="file-ready"><Check/> {file.name}</p>}<label className="photo-notes">Optional note<textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={500}/></label>{error&&<div className="live-alert error">{error}</div>}<footer><button onClick={close}>Cancel</button><button className="live-primary" disabled={!file||busy} onClick={submit}>{busy?"Uploading…":"Submit for review"}</button></footer></div></div>}
