"use client";

import { useCallback, useEffect, useState } from "react";
import { BarChart3, BedDouble, Building2, Check, ClipboardCheck, Clock3, Download, Eye, LayoutDashboard, LoaderCircle, LogOut, Plus, RefreshCw, Search, Settings, ShieldCheck, Trash2, UserPlus, Users, X } from "lucide-react";
import { authFetch } from "@/lib/auth-fetch";

type Profile={id:string;role:"dean"|"checker"|"student";full_name:string;email:string;age:number|null;grade:string|null;nationality:string|null;student_code:string|null};
type Floor={id:string;hall:string;floor_number:number;label:string};
type Room={id:string;floor_id:string;room_number:string;capacity:number;checker_id:string|null;active:boolean};
type Assignment={id:string;room_id:string;student_id:string;active:boolean};
type Template={id:string;name:string;check_time:string;days_of_week:number[];grace_minutes:number;active:boolean};
type Event={id:string;template_id:string;scheduled_for:string;opened_at:string|null;closed_at:string|null};
type Verification={id:string;event_id:string;student_id:string;checker_id:string;room_id:string;method:"qr"|"photo";status:"verified"|"photo_review"|"pending"|"absent";photo_path:string|null;verified_at:string};
type Data={profiles:Profile[];floors:Floor[];rooms:Room[];assignments:Assignment[];templates:Template[];events:Event[];verifications:Verification[]};
type View="Overview"|"Students"|"Rooms"|"Live check"|"Reports"|"Settings";

const empty:Data={profiles:[],floors:[],rooms:[],assignments:[],templates:[],events:[],verifications:[]};

export function DeanLive({onLogout}:{onLogout:()=>Promise<void>}){
 const [data,setData]=useState<Data>(empty);const[view,setView]=useState<View>("Overview");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[notice,setNotice]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{setData(await authFetch("/api/admin/bootstrap"))}catch(e){setError(e instanceof Error?e.message:"Could not load data")}finally{setLoading(false)}},[]);
 useEffect(()=>{queueMicrotask(load)},[load]);
 async function action(payload:Record<string,unknown>){setError("");try{await authFetch("/api/admin/manage",{method:"POST",body:JSON.stringify(payload)});setNotice("Changes saved");await load()}catch(e){setError(e instanceof Error?e.message:"Could not save changes")}}
 const students=data.profiles.filter(p=>p.role==="student"),checkers=data.profiles.filter(p=>p.role==="checker"),openEvent=data.events.find(e=>!e.closed_at),pendingPhotos=data.verifications.filter(v=>v.status==="photo_review");
 const nav:[[View,typeof LayoutDashboard],...Array<[View,typeof LayoutDashboard]>]=[["Overview",LayoutDashboard],["Live check",ClipboardCheck],["Students",Users],["Rooms",BedDouble],["Reports",BarChart3],["Settings",Settings]];
 return <main className="live-admin"><aside><div className="brand"><span className="crest">K</span><div><strong>Kingsway</strong><small>Room Check</small></div></div><nav>{nav.map(([name,Icon])=><button key={name} className={view===name?"active":""} onClick={()=>setView(name)}><Icon size={18}/>{name}</button>)}</nav><button className="admin-logout" onClick={onLogout}><LogOut size={17}/> Sign out</button></aside><section className="live-content"><header><div><span>DEAN ADMINISTRATION</span><h1>{view}</h1></div><button onClick={load}><RefreshCw size={16}/> Refresh</button></header>{error&&<div className="live-alert error"><ShieldCheck/>{error}<button onClick={()=>setError("")}><X/></button></div>}{notice&&<div className="live-alert success"><Check/>{notice}<button onClick={()=>setNotice("")}><X/></button></div>}{loading?<Loading/>:<>{view==="Overview"&&<Overview data={data} students={students} openEvent={openEvent} pendingPhotos={pendingPhotos}/>} {view==="Students"&&<StudentsView students={students} rooms={data.rooms} assignments={data.assignments} action={action}/>} {view==="Rooms"&&<RoomsView data={data} students={students} checkers={checkers} action={action}/>} {view==="Live check"&&<LiveView data={data} openEvent={openEvent} pendingPhotos={pendingPhotos} action={action}/>} {view==="Reports"&&<ReportsView data={data}/>} {view==="Settings"&&<SettingsView templates={data.templates} action={action}/>}</>}</section></main>
}

function Loading(){return <div className="live-loading"><LoaderCircle/><p>Loading secure residence data…</p></div>}

function Overview({data,students,openEvent,pendingPhotos}:{data:Data;students:Profile[];openEvent?:Event;pendingPhotos:Verification[]}){const verified=openEvent?data.verifications.filter(v=>v.event_id===openEvent.id&&v.status==="verified").length:0;const rate=students.length?Math.round(verified/students.length*100):0;return <><div className="live-stats"><Metric label="Active students" value={students.length}/><Metric label="Rooms" value={data.rooms.filter(r=>r.active).length}/><Metric label="Current completion" value={`${rate}%`}/><Metric label="Photos to review" value={pendingPhotos.length}/></div><section className="live-panel"><div className="live-panel-title"><div><span>{openEvent?"SESSION IN PROGRESS":"NO ACTIVE SESSION"}</span><h2>{openEvent?"Live room check":"Ready for the next check"}</h2></div><Clock3/></div>{openEvent?<ProgressRows data={data} event={openEvent}/>:<div className="empty-state"><ClipboardCheck/><h3>No room check is open</h3><p>Open a configured schedule from Live check when staff are ready.</p></div>}</section></>}
function Metric({label,value}:{label:string;value:string|number}){return <article><span>{label}</span><strong>{value}</strong></article>}
function ProgressRows({data,event}:{data:Data;event:Event}){return <div className="progress-rows">{data.floors.map(floor=>{const roomIds=data.rooms.filter(r=>r.floor_id===floor.id).map(r=>r.id);const expected=data.assignments.filter(a=>roomIds.includes(a.room_id)).length;const done=data.verifications.filter(v=>v.event_id===event.id&&roomIds.includes(v.room_id)&&v.status==="verified").length;const pct=expected?Math.round(done/expected*100):0;return <div key={floor.id}><div><strong>{floor.hall} · {floor.label}</strong><span>{done} of {expected} verified</span><b>{pct}%</b></div><i><span style={{width:`${pct}%`}}/></i></div>})}</div>}

function StudentsView({students,rooms,assignments,action}:{students:Profile[];rooms:Room[];assignments:Assignment[];action:(p:Record<string,unknown>)=>Promise<void>}){const[show,setShow]=useState(false);const[q,setQ]=useState("");const filtered=students.filter(s=>`${s.full_name} ${s.email} ${s.student_code}`.toLowerCase().includes(q.toLowerCase()));return <><div className="live-toolbar"><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search students"/></label><button className="live-primary" onClick={()=>setShow(true)}><UserPlus/> Add student</button></div><section className="live-table"><table><thead><tr><th>Student</th><th>Grade</th><th>Nationality</th><th>Room</th><th/></tr></thead><tbody>{filtered.map(student=>{const assignment=assignments.find(a=>a.student_id===student.id);const room=rooms.find(r=>r.id===assignment?.room_id);return <tr key={student.id}><td><strong>{student.full_name}</strong><small>{student.email}<br/>{student.student_code}</small></td><td>{student.grade||"—"}</td><td>{student.nationality||"—"}</td><td><select value={room?.id||""} onChange={e=>e.target.value?action({action:"assign_student",studentId:student.id,roomId:e.target.value}):action({action:"remove_assignment",studentId:student.id})}><option value="">Unassigned</option>{rooms.filter(r=>r.active).map(r=><option value={r.id} key={r.id}>{r.room_number}</option>)}</select></td><td><button className="danger-icon" onClick={()=>confirm(`Remove ${student.full_name}?`)&&action({action:"delete_student",id:student.id})}><Trash2/></button></td></tr>})}</tbody></table></section>{show&&<StudentModal close={()=>setShow(false)} action={action}/>}</>}
function StudentModal({close,action}:{close:()=>void;action:(p:Record<string,unknown>)=>Promise<void>}){const[form,setForm]=useState({fullName:"",email:"",age:"",grade:"Grade 9",nationality:""});return <div className="modal-backdrop"><form className="live-modal" onSubmit={async e=>{e.preventDefault();await action({action:"create_student",...form});close()}}><header><h2>Add student</h2><button type="button" onClick={close}><X/></button></header><label>Full name<input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><div><label>Age<input type="number" min="10" max="30" value={form.age} onChange={e=>setForm({...form,age:e.target.value})}/></label><label>Grade<select value={form.grade} onChange={e=>setForm({...form,grade:e.target.value})}>{[9,10,11,12].map(n=><option key={n}>Grade {n}</option>)}</select></label></div><label>Nationality<input value={form.nationality} onChange={e=>setForm({...form,nationality:e.target.value})}/></label><footer><button type="button" onClick={close}>Cancel</button><button className="live-primary">Send invitation</button></footer></form></div>}

function RoomsView({data,students,checkers,action}:{data:Data;students:Profile[];checkers:Profile[];action:(p:Record<string,unknown>)=>Promise<void>}){const[show,setShow]=useState(false);const[showFloor,setShowFloor]=useState(false);const[showChecker,setShowChecker]=useState(false);return <><div className="live-toolbar"><p>{data.rooms.length} rooms across {data.floors.length} floors · {checkers.length} checkers</p><div className="toolbar-actions"><button onClick={()=>setShowChecker(true)}><UserPlus/> Add checker</button><button onClick={()=>setShowFloor(true)}><Building2/> Add floor</button><button className="live-primary" onClick={()=>setShow(true)}><Plus/> Add room</button></div></div><div className="live-room-grid">{data.rooms.map(room=>{const floor=data.floors.find(f=>f.id===room.floor_id);const assigned=data.assignments.filter(a=>a.room_id===room.id);return <article key={room.id}><header><div><span>{floor?.hall} · {floor?.label}</span><h3>Room {room.room_number}</h3></div><b>{assigned.length}/{room.capacity}</b></header><label>Assigned checker<select value={room.checker_id||""} onChange={e=>action({action:"update_room",id:room.id,capacity:room.capacity,checkerId:e.target.value,active:room.active})}><option value="">No checker</option>{checkers.map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</select></label><div className="resident-list">{assigned.map(a=>{const student=students.find(s=>s.id===a.student_id);return <div key={a.id}><span>{student?.full_name||"Unknown"}</span><button onClick={()=>action({action:"remove_assignment",studentId:a.student_id})}><X/></button></div>})}{assigned.length<room.capacity&&<small>{room.capacity-assigned.length} bed{room.capacity-assigned.length!==1?"s":""} available</small>}</div></article>})}</div>{show&&<RoomModal floors={data.floors} checkers={checkers} close={()=>setShow(false)} action={action}/>} {showFloor&&<FloorModal close={()=>setShowFloor(false)} action={action}/>} {showChecker&&<CheckerModal close={()=>setShowChecker(false)} action={action}/>}</>}
function RoomModal({floors,checkers,close,action}:{floors:Floor[];checkers:Profile[];close:()=>void;action:(p:Record<string,unknown>)=>Promise<void>}){const[form,setForm]=useState({roomNumber:"",floorId:floors[0]?.id||"",capacity:"2",checkerId:""});return <div className="modal-backdrop"><form className="live-modal" onSubmit={async e=>{e.preventDefault();await action({action:"create_room",...form});close()}}><header><h2>Add room</h2><button type="button" onClick={close}><X/></button></header>{!floors.length&&<p className="inline-warning">Create a floor in Supabase before adding rooms.</p>}<label>Room number<input required value={form.roomNumber} onChange={e=>setForm({...form,roomNumber:e.target.value})}/></label><label>Floor<select required value={form.floorId} onChange={e=>setForm({...form,floorId:e.target.value})}>{floors.map(f=><option value={f.id} key={f.id}>{f.hall} · {f.label}</option>)}</select></label><label>Capacity<input type="number" min="1" max="8" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/></label><label>Checker<select value={form.checkerId} onChange={e=>setForm({...form,checkerId:e.target.value})}><option value="">Assign later</option>{checkers.map(c=><option value={c.id} key={c.id}>{c.full_name}</option>)}</select></label><footer><button type="button" onClick={close}>Cancel</button><button className="live-primary" disabled={!floors.length}>Create room</button></footer></form></div>}

function FloorModal({close,action}:{close:()=>void;action:(p:Record<string,unknown>)=>Promise<void>}){const[form,setForm]=useState({hall:"",floorNumber:"1",label:"1st floor"});return <div className="modal-backdrop"><form className="live-modal" onSubmit={async e=>{e.preventDefault();await action({action:"create_floor",...form});close()}}><header><h2>Add residence floor</h2><button type="button" onClick={close}><X/></button></header><label>Residence hall<input required placeholder="North Hall" value={form.hall} onChange={e=>setForm({...form,hall:e.target.value})}/></label><div><label>Floor number<input required type="number" min="0" max="30" value={form.floorNumber} onChange={e=>setForm({...form,floorNumber:e.target.value})}/></label><label>Display label<input required placeholder="1st floor" value={form.label} onChange={e=>setForm({...form,label:e.target.value})}/></label></div><footer><button type="button" onClick={close}>Cancel</button><button className="live-primary">Create floor</button></footer></form></div>}

function CheckerModal({close,action}:{close:()=>void;action:(p:Record<string,unknown>)=>Promise<void>}){const[form,setForm]=useState({fullName:"",email:""});return <div className="modal-backdrop"><form className="live-modal" onSubmit={async e=>{e.preventDefault();await action({action:"create_checker",...form});close()}}><header><h2>Invite a checker</h2><button type="button" onClick={close}><X/></button></header><p className="modal-copy">The checker receives a secure email invitation and can then be assigned to one or more rooms.</p><label>Full name<input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></label><label>Email address<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><footer><button type="button" onClick={close}>Cancel</button><button className="live-primary">Send invitation</button></footer></form></div>}

function LiveView({data,openEvent,pendingPhotos,action}:{data:Data;openEvent?:Event;pendingPhotos:Verification[];action:(p:Record<string,unknown>)=>Promise<void>}){const[template,setTemplate]=useState(data.templates[0]?.id||"");async function viewPhoto(id:string){try{const result=await authFetch(`/api/admin/photo/${id}`);window.open(result.url,"_blank","noopener,noreferrer")}catch(error){alert(error instanceof Error?error.message:"Photo could not be opened")}}return <><div className="live-session-card"><div><span>{openEvent?"ACTIVE SESSION":"START A ROOM CHECK"}</span><h2>{openEvent?data.templates.find(t=>t.id===openEvent.template_id)?.name:"Choose a configured schedule"}</h2></div>{openEvent?<button className="danger-button" onClick={()=>action({action:"close_event",id:openEvent.id})}>Close session</button>:<div><select value={template} onChange={e=>setTemplate(e.target.value)}>{data.templates.filter(t=>t.active).map(t=><option key={t.id} value={t.id}>{t.name} · {t.check_time.slice(0,5)}</option>)}</select><button className="live-primary" disabled={!template} onClick={()=>action({action:"open_event",templateId:template})}>Open now</button></div>}</div>{openEvent&&<ProgressRows data={data} event={openEvent}/>}<section className="live-panel"><div className="live-panel-title"><div><span>PHOTO EXCEPTIONS</span><h2>Awaiting Dean review</h2></div><b>{pendingPhotos.length}</b></div>{pendingPhotos.length?pendingPhotos.map(v=>{const student=data.profiles.find(p=>p.id===v.student_id);const room=data.rooms.find(r=>r.id===v.room_id);return <div className="review-row" key={v.id}><div><strong>{student?.full_name}</strong><span>Room {room?.room_number} · {new Date(v.verified_at).toLocaleString()}</span></div><button onClick={()=>viewPhoto(v.id)}><Eye/> View photo</button><button onClick={()=>action({action:"review_photo",id:v.id,approved:false})}>Reject</button><button className="live-primary" onClick={()=>action({action:"review_photo",id:v.id,approved:true})}>Approve</button></div>}):<div className="empty-state"><Check/><h3>Review queue is clear</h3></div>}</section></>}

// The reporting clock is intentionally captured when the view renders; filters are user-driven afterward.
// eslint-disable-next-line react-hooks/purity
function ReportsView({data}:{data:Data}){const[period,setPeriod]=useState("7");const cutoff=Date.now()-Number(period)*86400000;const records=data.verifications.filter(v=>new Date(v.verified_at).getTime()>=cutoff);const events=data.events.filter(e=>new Date(e.scheduled_for).getTime()>=cutoff);const verified=records.filter(v=>v.status==="verified").length,photos=records.filter(v=>v.method==="photo").length,absent=records.filter(v=>v.status==="absent").length,total=records.length,rate=total?Math.round(verified/total*1000)/10:0;function download(){const rows=["date,student,room,method,status",...records.map(v=>[v.verified_at,data.profiles.find(p=>p.id===v.student_id)?.full_name||v.student_id,data.rooms.find(r=>r.id===v.room_id)?.room_number||v.room_id,v.method,v.status].map(x=>`"${String(x).replaceAll('"','""')}"`).join(","))];const url=URL.createObjectURL(new Blob([rows.join("\n")],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download=`room-check-${period}-day-report.csv`;a.click();URL.revokeObjectURL(url)}return <><div className="live-toolbar"><div className="report-filter"><span>Reporting period</span><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="1">Today</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="365">This year</option></select></div><button className="live-primary" onClick={download}><Download/> Export CSV</button></div><div className="live-stats"><Metric label="Attendance records" value={total}/><Metric label="Verification rate" value={`${rate}%`}/><Metric label="Photo exceptions" value={photos}/><Metric label="Confirmed absent" value={absent}/></div><section className="live-panel"><div className="live-panel-title"><div><span>SESSION REPORTS</span><h2>Completion history</h2></div></div>{events.map(event=>{const eventRecords=data.verifications.filter(v=>v.event_id===event.id);const count=eventRecords.filter(v=>v.status==="verified").length;const eventRate=eventRecords.length?Math.round(count/eventRecords.length*100):0;return <div className="report-row" key={event.id}><div><strong>{data.templates.find(t=>t.id===event.template_id)?.name||"Room check"}</strong><span>{new Date(event.scheduled_for).toLocaleString()}</span></div><b>{count}/{eventRecords.length} · {eventRate}%</b><em>{event.closed_at?"Closed":"Open"}</em></div>})}{!events.length&&<div className="empty-state"><BarChart3/><h3>No sessions in this period</h3></div>}</section></>}

function SettingsView({templates,action}:{templates:Template[];action:(p:Record<string,unknown>)=>Promise<void>}){const[show,setShow]=useState(false);return <><div className="live-toolbar"><p>Configure the checks your team can open.</p><button className="live-primary" onClick={()=>setShow(true)}><Plus/> Add schedule</button></div><section className="live-panel"><div className="live-panel-title"><div><span>RECURRING SCHEDULES</span><h2>Room check times</h2></div></div>{templates.map(t=><div className="schedule-live" key={t.id}><Clock3/><div><strong>{t.name}</strong><span>{t.check_time.slice(0,5)} · {t.grace_minutes} minute window · {t.days_of_week.length} days/week</span></div><label className="switch"><input type="checkbox" checked={t.active} onChange={e=>action({action:"save_schedule",id:t.id,name:t.name,time:t.check_time,days:t.days_of_week,graceMinutes:t.grace_minutes,active:e.target.checked})}/><span/></label></div>)}</section>{show&&<ScheduleModal close={()=>setShow(false)} action={action}/>}</>}

function ScheduleModal({close,action}:{close:()=>void;action:(p:Record<string,unknown>)=>Promise<void>}){const[form,setForm]=useState({name:"",time:"22:00",graceMinutes:"20"});const[days,setDays]=useState([0,1,2,3,4,5,6]);const labels=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];return <div className="modal-backdrop"><form className="live-modal" onSubmit={async e=>{e.preventDefault();await action({action:"save_schedule",...form,days,active:true});close()}}><header><h2>Add room check schedule</h2><button type="button" onClick={close}><X/></button></header><label>Schedule name<input required placeholder="Night Check" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div><label>Start time<input required type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></label><label>Verification window<input required type="number" min="5" max="120" value={form.graceMinutes} onChange={e=>setForm({...form,graceMinutes:e.target.value})}/></label></div><fieldset className="day-picker"><legend>Active days</legend>{labels.map((label,index)=><label key={label}><input type="checkbox" checked={days.includes(index)} onChange={()=>setDays(current=>current.includes(index)?current.filter(day=>day!==index):[...current,index].sort())}/><span>{label}</span></label>)}</fieldset><footer><button type="button" onClick={close}>Cancel</button><button className="live-primary" disabled={!days.length}>Create schedule</button></footer></form></div>}
