"use client";

import { createContext, useCallback, useContext, useEffect, useRef, useState } from "react";
import { BarChart3, BedDouble, Building2, Check, ClipboardCheck, Clock3, Download, Edit3, Eye, LayoutDashboard, LoaderCircle, LogOut, Plus, RefreshCw, Search, Settings, ShieldCheck, Trash2, UserCog, Users, X } from "lucide-react";
import { authFetch } from "@/lib/auth-fetch";
import { ResidenceRequests } from "@/components/residence-requests";
import { ActivityLog } from "@/components/activity-log";
import { csvCell } from "@/lib/csv";
import Image from "next/image";
import Link from "next/link";

type Role="dean"|"checker"|"student";
type Profile={id:string;role:Role;full_name:string;email:string;age:number|null;grade:string|null;nationality:string|null;student_code:string|null};
type Floor={id:string;hall:string;floor_number:number;label:string};
type Room={id:string;floor_id:string;room_number:string;capacity:number;checker_id:string|null;active:boolean};
type Assignment={id:string;room_id:string;student_id:string;active:boolean};
type Template={id:string;name:string;check_time:string;days_of_week:number[];grace_minutes:number;active:boolean};
type Event={id:string;template_id:string;scheduled_for:string;opened_at:string|null;closed_at:string|null};
type Verification={id:string;event_id:string;student_id:string;checker_id:string;room_id:string;method:"qr"|"photo";status:"verified"|"photo_review"|"pending"|"absent";photo_path:string|null;verified_at:string};
type Data={viewerId:string;profiles:Profile[];floors:Floor[];rooms:Room[];assignments:Assignment[];templates:Template[];events:Event[];verifications:Verification[]};
type View="Room Assignments"|"Checker Coverage"|"Occupancy"|"Overview"|"Students"|"Users & Roles"|"Rooms"|"Live check"|"Reports"|"Settings"|"Maintenance"|"Activity";
type Action=(payload:Record<string,unknown>,message?:string)=>Promise<boolean>;
const ActionContext=createContext({error:"",saving:false});
const empty:Data={viewerId:"",profiles:[],floors:[],rooms:[],assignments:[],templates:[],events:[],verifications:[]};

export function DeanLive({onLogout}:{onLogout:()=>Promise<void>}){
 const[data,setData]=useState<Data>(empty),[view,setView]=useState<View>("Overview"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{setError("");try{setData(await authFetch("/api/admin/bootstrap"))}catch(e){setError(e instanceof Error?e.message:"Could not load data")}finally{setLoading(false)}},[]);
 useEffect(()=>{queueMicrotask(load)},[load]);
 const[saving,setSaving]=useState(false);const actionLock=useRef(false);
 const action:Action=async(payload,message="Changes saved")=>{if(actionLock.current)return false;actionLock.current=true;setSaving(true);setError("");setNotice("");try{await authFetch("/api/admin/manage",{method:"POST",body:JSON.stringify(payload)});setNotice(message);await load();return true}catch(e){setError(e instanceof Error?e.message:"Could not save changes");return false}finally{actionLock.current=false;setSaving(false)}};
 const residents=data.profiles,checkers=data.profiles.filter(p=>p.role==="checker"),openEvent=data.events.find(e=>!e.closed_at),pendingPhotos=data.verifications.filter(v=>v.status==="photo_review");
 const nav:[View,typeof LayoutDashboard][]=[["Overview",LayoutDashboard],["Live check",ClipboardCheck],["Students",Users],["Users & Roles",UserCog],["Rooms",BedDouble],["Room Assignments",BedDouble],["Checker Coverage",ShieldCheck],["Occupancy",Building2],["Reports",BarChart3],["Maintenance",Building2],["Activity",Clock3],["Settings",Settings]];
 return <ActionContext.Provider value={{error,saving}}><main className="live-admin"><aside><div className="brand"><span className="crest">K</span><div><strong>Kingsway</strong><small>Room Check</small></div></div><nav>{nav.map(([name,Icon])=><button key={name} className={view===name?"active":""} onClick={()=>setView(name)}><Icon size={18}/>{name}</button>)}</nav><button className="admin-logout" onClick={onLogout}><LogOut size={17}/> Sign out</button></aside><section className="live-content"><header><div><span>DEAN ADMINISTRATION</span><h1>{view}</h1></div><div className="header-actions"><Link href="/student">My QR</Link><button onClick={load} disabled={loading||saving}><RefreshCw size={16}/> Refresh</button></div></header>{error&&<div className="live-alert error"><ShieldCheck/>{error}<button onClick={()=>setError("")}><X/></button></div>}{notice&&<div className="live-alert success"><Check/>{notice}<button onClick={()=>setNotice("")}><X/></button></div>}{loading?<Loading/>:!data.viewerId?<div className="empty-state"><h3>Residence data could not be loaded</h3><p>No counts or assignments are shown until the connection succeeds.</p><button onClick={load}>Retry loading</button></div>:<>{view==="Overview"&&<Overview data={data} residents={residents} openEvent={openEvent} pendingPhotos={pendingPhotos} navigate={setView}/>} {view==="Room Assignments"&&<AssignmentsView data={data} action={action}/>} {view==="Checker Coverage"&&<CoverageView data={data} action={action} navigate={setView}/>} {view==="Occupancy"&&<OccupancyView data={data} navigate={setView}/>} {view==="Students"&&<StudentsView residents={residents} viewerId={data.viewerId} rooms={data.rooms} assignments={data.assignments} action={action}/>} {view==="Users & Roles"&&<UsersView data={data} action={action}/>} {view==="Rooms"&&<RoomsView data={data} students={residents} checkers={checkers} action={action}/>} {view==="Live check"&&<LiveView data={data} openEvent={openEvent} pendingPhotos={pendingPhotos} action={action}/>} {view==="Reports"&&<ReportsView data={data}/>} {view==="Maintenance"&&<ResidenceRequests dean rooms={data.rooms.filter(r=>r.active)}/>} {view==="Activity"&&<ActivityLog/>} {view==="Settings"&&<SettingsView templates={data.templates} action={action}/>}</>}</section></main></ActionContext.Provider>
}

function Loading(){return <div className="live-loading"><LoaderCircle/><p>Loading secure residence data…</p></div>}
function Metric({label,value,onClick}:{label:string;value:string|number;onClick?:()=>void}){const content=<><span>{label}</span><strong>{value}</strong></>;return onClick?<button className="metric-link" onClick={onClick}>{content}</button>:<article>{content}</article>}
function Overview({data,residents,openEvent,pendingPhotos,navigate}:{data:Data;residents:Profile[];openEvent?:Event;pendingPhotos:Verification[];navigate:(view:View)=>void}){const verified=openEvent?data.verifications.filter(v=>v.event_id===openEvent.id&&v.status==="verified").length:0,rate=data.assignments.length?Math.min(100,Math.round(verified/data.assignments.length*100)):0;return <><div className="live-stats"><Metric onClick={()=>navigate("Users & Roles")} label="Accounts" value={residents.length}/><Metric onClick={()=>navigate("Room Assignments")} label="Assigned residents" value={data.assignments.length}/><Metric onClick={()=>navigate("Live check")} label="Current completion" value={`${rate}%`}/><Metric onClick={()=>navigate("Live check")} label="Photos to review" value={pendingPhotos.length}/></div><section className="live-panel"><div className="live-panel-title"><div><span>{openEvent?"SESSION IN PROGRESS":"NO ACTIVE SESSION"}</span><h2>{openEvent?"Live room check":"Ready for the next check"}</h2></div><Clock3/></div>{data.rooms.some(r=>r.active&&!r.checker_id)&&<p className="inline-warning">Some active rooms have no assigned checker. <button onClick={()=>navigate("Checker Coverage")}>Assign checker coverage</button>.</p>}{openEvent?<ProgressRows data={data} event={openEvent}/>:<div className="empty-state"><ClipboardCheck/><h3>No room check is open</h3><p>Open a configured schedule when staff are ready.</p><button className="live-primary" onClick={()=>navigate("Live check")}>Go to live check</button></div>}</section></>}
function ProgressRows({data,event}:{data:Data;event:Event}){return <div className="progress-rows">{data.floors.map(f=>{const roomIds=data.rooms.filter(r=>r.floor_id===f.id).map(r=>r.id),expected=data.assignments.filter(a=>roomIds.includes(a.room_id)).length,done=data.verifications.filter(v=>v.event_id===event.id&&roomIds.includes(v.room_id)&&v.status==="verified").length,pct=expected?Math.round(done/expected*100):0;return <div key={f.id}><div><strong>{f.hall} · {f.label}</strong><span>{done} of {expected} verified</span><b>{pct}%</b></div><i><span style={{width:`${pct}%`}}/></i></div>})}</div>}

function StudentsView({residents,viewerId,rooms,assignments,action}:{residents:Profile[];viewerId:string;rooms:Room[];assignments:Assignment[];action:Action}){const[editing,setEditing]=useState<Profile|null>(null),[q,setQ]=useState("");const filtered=residents.filter(s=>`${s.full_name} ${s.email} ${s.student_code}`.toLowerCase().includes(q.toLowerCase()));return <><div className="live-toolbar"><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search residents"/></label><p>Accounts appear after the first school Google sign-in.</p></div><section className="live-table"><table><thead><tr><th>Resident account</th><th>Role / Grade</th><th>Nationality</th><th>Room</th><th>Actions</th></tr></thead><tbody>{filtered.map(student=>{const assignment=assignments.find(a=>a.student_id===student.id),room=rooms.find(r=>r.id===assignment?.room_id);return <tr key={student.id}><td><strong>{student.full_name}{student.id===viewerId?" (You)":""}</strong><small>{student.email}<br/>{student.student_code}</small></td><td><span className={`role-pill ${student.role}`}>{student.role}</span><small>{student.grade||"No grade set"}</small></td><td>{student.nationality||"—"}</td><td><select value={room?.id||""} onChange={e=>void(e.target.value?action({action:"assign_student",studentId:student.id,roomId:e.target.value},"Room assignment updated"):action({action:"remove_assignment",studentId:student.id},"Room assignment removed"))}><option value="">Unassigned</option>{rooms.filter(r=>r.active).map(r=><option value={r.id} key={r.id}>{r.room_number}</option>)}</select></td><td><div className="row-actions"><button title="Edit resident" onClick={()=>setEditing(student)}><Edit3/></button><button className="danger-icon" disabled={student.id===viewerId} title="Delete resident" onClick={()=>confirm(`Permanently remove ${student.full_name}?`)&&void action({action:"delete_user",id:student.id},"Resident removed")}><Trash2/></button></div></td></tr>})}</tbody></table></section>{editing&&<EditStudentModal profile={editing} close={()=>setEditing(null)} action={action}/>}</>}
function EditStudentModal({profile,close,action}:{profile:Profile;close:()=>void;action:Action}){const[form,setForm]=useState({fullName:profile.full_name,age:String(profile.age??""),grade:profile.grade??"",nationality:profile.nationality??""});return <ModalForm title="Edit resident" close={close} submit={async()=>{if(await action({action:"update_profile",id:profile.id,...form},"Resident profile updated"))close()}}><label>Full name<input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></label><div><label>Age<input type="number" min="10" max="30" value={form.age} onChange={e=>setForm({...form,age:e.target.value})}/></label><label>Grade<input value={form.grade} onChange={e=>setForm({...form,grade:e.target.value})}/></label></div><label>Nationality<input value={form.nationality} onChange={e=>setForm({...form,nationality:e.target.value})}/></label><SubmitButtons close={close} label="Save changes"/></ModalForm>}

function UsersView({data,action}:{data:Data;action:Action}){const[q,setQ]=useState(""),[filter,setFilter]=useState<"all"|Role>("all"),[roomsFor,setRoomsFor]=useState<Profile|null>(null);const users=data.profiles.filter(u=>(filter==="all"||u.role===filter)&&`${u.full_name} ${u.email} ${u.role}`.toLowerCase().includes(q.toLowerCase()));async function changeRole(user:Profile,role:Role){if(user.id===data.viewerId||!confirm(`Change ${user.full_name} from ${user.role} to ${role}?`))return;await action({action:"set_role",id:user.id,role},`${user.full_name} is now a ${role}`)}return <><div className="live-toolbar user-toolbar"><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search all users"/></label><div className="toolbar-actions"><select value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}><option value="all">All roles</option><option value="dean">Deans</option><option value="checker">Checkers</option><option value="student">Students</option></select></div></div><section className="live-table"><table><thead><tr><th>User</th><th>Role</th><th>Checker rooms</th><th>Change role</th><th/></tr></thead><tbody>{users.map(user=>{const assigned=data.rooms.filter(room=>room.checker_id===user.id);return <tr key={user.id}><td><strong>{user.full_name}{user.id===data.viewerId?" (You)":""}</strong><small>{user.email}<br/>{user.student_code||"Staff account"}</small></td><td><span className={`role-pill ${user.role}`}>{user.role}</span></td><td>{user.role==="checker"?<button className="room-assignment-link" onClick={()=>setRoomsFor(user)}>{assigned.length?assigned.map(room=>room.room_number).join(", "):"Assign rooms"}</button>:"—"}</td><td><select disabled={user.id===data.viewerId} value={user.role} onChange={e=>void changeRole(user,e.target.value as Role)}><option value="student">Student</option><option value="checker">Checker</option><option value="dean">Dean</option></select></td><td><button className="danger-icon" disabled={user.id===data.viewerId} title="Delete account" onClick={()=>confirm(`Permanently delete ${user.full_name}'s account?`)&&void action({action:"delete_user",id:user.id},"User account deleted")}><Trash2/></button></td></tr>})}</tbody></table></section>{roomsFor&&<CheckerRoomsModal checker={roomsFor} rooms={data.rooms} floors={data.floors} close={()=>setRoomsFor(null)} action={action}/>} </>}
function CheckerRoomsModal({checker,rooms,floors,close,action}:{checker:Profile;rooms:Room[];floors:Floor[];close:()=>void;action:Action}){const[selected,setSelected]=useState(()=>rooms.filter(r=>r.checker_id===checker.id).map(r=>r.id));return <ModalForm title="Assign checker rooms" subtitle={checker.full_name} wide close={close} submit={async()=>{if(await action({action:"set_checker_rooms",checkerId:checker.id,roomIds:selected},"Checker room assignments updated"))close()}}><div className="floor-selection">{floors.map(f=>{const ids=rooms.filter(r=>r.active&&r.floor_id===f.id).map(r=>r.id);return <button type="button" key={f.id} onClick={()=>setSelected(current=>ids.every(id=>current.includes(id))?current.filter(id=>!ids.includes(id)):[...new Set([...current,...ids])])}>{f.hall} · {f.label}</button>})}</div><p>Select a floor to toggle all its rooms. Selecting another checker’s room transfers responsibility.</p><div className="room-check-grid">{rooms.filter(r=>r.active).map(room=>{const floor=floors.find(f=>f.id===room.floor_id),occupied=room.checker_id&&room.checker_id!==checker.id;return <label key={room.id}><input type="checkbox" checked={selected.includes(room.id)} onChange={()=>setSelected(current=>current.includes(room.id)?current.filter(id=>id!==room.id):[...current,room.id])}/><span><strong>Room {room.room_number}</strong><small>{floor?.hall} · {floor?.label}{occupied?" · Reassign":""}</small></span></label>})}</div><SubmitButtons close={close} label="Save assignments"/></ModalForm>}

function RoomsView({data,students,checkers,action}:{data:Data;students:Profile[];checkers:Profile[];action:Action}){const[show,setShow]=useState(false),[showFloor,setShowFloor]=useState(false),[editing,setEditing]=useState<Room|null>(null);return <><div className="live-toolbar"><p>{data.rooms.length} rooms across {data.floors.length} floors · {checkers.length} checkers</p><div className="toolbar-actions"><button onClick={()=>setShowFloor(true)}><Building2/> Add floor</button><button className="live-primary" onClick={()=>setShow(true)}><Plus/> Add room</button></div></div><div className="live-room-grid">{data.rooms.map(room=>{const floor=data.floors.find(f=>f.id===room.floor_id),assigned=data.assignments.filter(a=>a.room_id===room.id);return <article className={!room.active?"inactive-room":""} key={room.id}><header><div><span>{floor?.hall} · {floor?.label}</span><h3>Room {room.room_number}</h3></div><div><b>{assigned.length}/{room.capacity}</b><button title="Edit room" onClick={()=>setEditing(room)}><Edit3 size={16}/></button></div></header><label>Assigned checker<select value={room.checker_id||""} onChange={e=>void action({action:"update_room",id:room.id,checkerId:e.target.value,active:room.active},"Checker assignment updated")}><option value="">No checker</option>{checkers.map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</select></label><div className="resident-list">{assigned.map(a=><div key={a.id}><span>{students.find(s=>s.id===a.student_id)?.full_name||"Unknown"}</span><button title="Remove room assignment" onClick={()=>void action({action:"remove_assignment",studentId:a.student_id},"Student removed from room")}><X/></button></div>)}{assigned.length<room.capacity&&<small>{room.capacity-assigned.length} bed{room.capacity-assigned.length!==1?"s":""} available</small>}</div><button className="room-status-button" onClick={()=>void action({action:"update_room",id:room.id,checkerId:room.checker_id,active:!room.active},room.active?"Room deactivated":"Room activated")}>{room.active?"Deactivate room":"Activate room"}</button></article>})}</div>{show&&<RoomModal floors={data.floors} checkers={checkers} close={()=>setShow(false)} action={action}/>} {showFloor&&<FloorModal close={()=>setShowFloor(false)} action={action}/>} {editing&&<RoomModal room={editing} floors={data.floors} checkers={checkers} close={()=>setEditing(null)} action={action}/>}</>}
function RoomModal({floors,checkers,close,action,room}:{floors:Floor[];checkers:Profile[];close:()=>void;action:Action;room?:Room}){const[form,setForm]=useState({roomNumber:room?.room_number??"",floorId:room?.floor_id??floors[0]?.id??"",capacity:String(room?.capacity??2),checkerId:room?.checker_id??""});return <ModalForm title={room?"Edit room":"Add room"} close={close} submit={async()=>{if(await action({action:room?"update_room":"create_room",id:room?.id,...form},"Room created"))close()}}>{!floors.length&&<p className="inline-warning">Create a floor before adding rooms.</p>}<label>Room number<input required value={form.roomNumber} onChange={e=>setForm({...form,roomNumber:e.target.value})}/></label><label>Floor<select required value={form.floorId} onChange={e=>setForm({...form,floorId:e.target.value})}>{floors.map(f=><option value={f.id} key={f.id}>{f.hall} · {f.label}</option>)}</select></label><div><label>Capacity<input type="number" min="1" max="8" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/></label><label>Checker<select value={form.checkerId} onChange={e=>setForm({...form,checkerId:e.target.value})}><option value="">Assign later</option>{checkers.map(c=><option value={c.id} key={c.id}>{c.full_name}</option>)}</select></label></div><SubmitButtons close={close} label={room?"Save room":"Create room"} disabled={!floors.length}/></ModalForm>}
function FloorModal({close,action}:{close:()=>void;action:Action}){const[form,setForm]=useState({hall:"",floorNumber:"1",label:"Floor One"});return <ModalForm title="Add residence floor" close={close} submit={async()=>{if(await action({action:"create_floor",...form},"Floor created"))close()}}><label>Residence hall<input required placeholder="Boys Dorm or Girls Dorm" value={form.hall} onChange={e=>setForm({...form,hall:e.target.value})}/></label><div><label>Floor number<input required type="number" min="0" max="30" value={form.floorNumber} onChange={e=>setForm({...form,floorNumber:e.target.value})}/></label><label>Display label<input required placeholder="Floor One" value={form.label} onChange={e=>setForm({...form,label:e.target.value})}/></label></div><SubmitButtons close={close} label="Create floor"/></ModalForm>}

function LiveView({data,openEvent,pendingPhotos,action}:{data:Data;openEvent?:Event;pendingPhotos:Verification[];action:Action}){const[template,setTemplate]=useState(data.templates.find(t=>t.active)?.id||"");const[photoUrl,setPhotoUrl]=useState("");async function viewPhoto(id:string){try{const result=await authFetch(`/api/admin/photo/${id}`);setPhotoUrl(result.url)}catch(e){alert(e instanceof Error?e.message:"Photo could not be opened")}}return <><div className="live-session-card"><div><span>{openEvent?"ACTIVE SESSION":"START A ROOM CHECK"}</span><h2>{openEvent?data.templates.find(t=>t.id===openEvent.template_id)?.name:"Choose a configured schedule"}</h2></div>{openEvent?<button className="danger-button" onClick={()=>confirm("Close this room check and mark every unverified student absent?")&&void action({action:"close_event",id:openEvent.id},"Room check closed")}>Close session</button>:<div><select aria-label="Room check schedule" value={template} onChange={e=>setTemplate(e.target.value)}>{data.templates.filter(t=>t.active).map(t=><option key={t.id} value={t.id}>{t.name} · {t.check_time.slice(0,5)}</option>)}</select><button className="live-primary" disabled={!template} onClick={()=>void action({action:"open_event",templateId:template},"Room check opened")}>Open now</button></div>}</div>{openEvent&&<ProgressRows data={data} event={openEvent}/>}<section className="live-panel"><div className="live-panel-title"><div><span>PHOTO EXCEPTIONS</span><h2>Awaiting Dean review</h2></div><b>{pendingPhotos.length}</b></div>{pendingPhotos.length?pendingPhotos.map(v=>{const student=data.profiles.find(p=>p.id===v.student_id),room=data.rooms.find(r=>r.id===v.room_id);return <div className="review-row" key={v.id}><div><strong>{student?.full_name}</strong><span>Room {room?.room_number} · {new Date(v.verified_at).toLocaleString()}</span></div><button onClick={()=>void viewPhoto(v.id)}><Eye/> View photo</button><button onClick={()=>void action({action:"review_photo",id:v.id,approved:false},"Photo rejected; student marked absent")}>Reject</button><button className="live-primary" onClick={()=>void action({action:"review_photo",id:v.id,approved:true},"Photo approved")}>Approve</button></div>}):<div className="empty-state"><Check/><h3>Review queue is clear</h3></div>}</section>{photoUrl&&<div className="modal-backdrop"><div className="photo-live-modal"><header><h2>Photo evidence</h2><button title="Close photo" onClick={()=>setPhotoUrl("")}><X/></button></header><Image unoptimized src={photoUrl} alt="Room check photo submitted for Dean review" width={900} height={900} style={{width:"100%",height:"auto",maxHeight:"65vh",objectFit:"contain"}}/><p>The private photo link expires after one minute.</p></div></div>}</>}

function ReportsView({data}:{data:Data}){
 const[period,setPeriod]=useState("7"),[records,setRecords]=useState<Verification[]>([]),[events,setEvents]=useState<Event[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let active=true;authFetch(`/api/admin/reports?days=${period}`).then(d=>{if(active){setRecords(d.records);setEvents(d.events);setError("")}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[period]);
 const verified=records.filter(v=>v.status==="verified").length,photos=records.filter(v=>v.method==="photo").length,absent=records.filter(v=>v.status==="absent").length,total=records.length,rate=total?Math.round(verified/total*1000)/10:0;
 function download(){const rows=["date,student,room,method,status",...records.map(v=>[v.verified_at,data.profiles.find(p=>p.id===v.student_id)?.full_name||v.student_id,data.rooms.find(r=>r.id===v.room_id)?.room_number||v.room_id,v.method,v.status].map(csvCell).join(","))],url=URL.createObjectURL(new Blob([rows.join("\n")],{type:"text/csv"})),a=document.createElement("a");a.href=url;a.download=`room-check-${period}-day-report.csv`;a.click();URL.revokeObjectURL(url)}
 return <><div className="live-toolbar"><div className="report-filter"><span>Reporting period</span><select value={period} onChange={e=>{setLoading(true);setPeriod(e.target.value)}}><option value="1">Last 24 hours</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="365">Last 365 days</option></select></div><button className="live-primary" disabled={loading||!!error||!records.length} onClick={download}><Download/> Export CSV</button></div>{error&&<div className="live-alert error">{error}</div>}{loading?<Loading/>:!error&&<><div className="live-stats"><Metric label="Attendance records" value={total}/><Metric label="Verification rate" value={`${rate}%`}/><Metric label="Photo exceptions" value={photos}/><Metric label="Confirmed absent" value={absent}/></div><section className="live-panel"><div className="live-panel-title"><div><span>SESSION REPORTS</span><h2>Completion history</h2></div></div>{events.map(event=>{const eventRecords=records.filter(v=>v.event_id===event.id),count=eventRecords.filter(v=>v.status==="verified").length,eventRate=eventRecords.length?Math.round(count/eventRecords.length*100):0;return <div className="report-row" key={event.id}><div><strong>{data.templates.find(t=>t.id===event.template_id)?.name||"Room check"}</strong><span>{new Date(event.scheduled_for).toLocaleString()}</span></div><b>{count}/{eventRecords.length} · {eventRate}%</b><em>{event.closed_at?"Closed":"Open"}</em></div>})}{!events.length&&<div className="empty-state"><BarChart3/><h3>No sessions in this period</h3></div>}</section></>}</>
}

function SettingsView({templates,action}:{templates:Template[];action:Action}){const[show,setShow]=useState(false),[editing,setEditing]=useState<Template|null>(null);return <><div className="live-toolbar"><p>Configure the checks your team can open.</p><button className="live-primary" onClick={()=>setShow(true)}><Plus/> Add schedule</button></div><section className="live-panel"><div className="live-panel-title"><div><span>RECURRING SCHEDULES</span><h2>Room check times</h2></div></div>{templates.map(t=><div className="schedule-live" key={t.id}><Clock3/><div><strong>{t.name}</strong><span>{t.check_time.slice(0,5)} · {t.grace_minutes} minute window · {t.days_of_week.length} days/week</span></div><label className="switch"><input type="checkbox" checked={t.active} onChange={e=>void action({action:"save_schedule",id:t.id,name:t.name,time:t.check_time,days:t.days_of_week,graceMinutes:t.grace_minutes,active:e.target.checked},e.target.checked?"Schedule enabled":"Schedule disabled")}/><span/></label><button title="Edit schedule" onClick={()=>setEditing(t)}><Edit3/></button><button className="danger-icon" title="Delete schedule" onClick={()=>confirm(`Delete ${t.name}?`)&&void action({action:"delete_schedule",id:t.id},"Schedule deleted")}><Trash2/></button></div>)}</section>{show&&<ScheduleModal close={()=>setShow(false)} action={action}/>} {editing&&<ScheduleModal template={editing} close={()=>setEditing(null)} action={action}/>}</>}
function ScheduleModal({close,action,template}:{close:()=>void;action:Action;template?:Template}){const[form,setForm]=useState({name:template?.name??"",time:template?.check_time.slice(0,5)??"22:00",graceMinutes:String(template?.grace_minutes??20)}),[days,setDays]=useState(template?.days_of_week??[0,1,2,3,4,5,6]),labels=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];return <ModalForm title={template?"Edit room check schedule":"Add room check schedule"} close={close} submit={async()=>{if(await action({action:"save_schedule",id:template?.id,...form,days,active:template?.active??true},"Schedule created"))close()}}><label>Schedule name<input required placeholder="Night Check" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div><label>Start time<input required type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></label><label>Verification window<input required type="number" min="5" max="120" value={form.graceMinutes} onChange={e=>setForm({...form,graceMinutes:e.target.value})}/></label></div><fieldset className="day-picker"><legend>Active days</legend>{labels.map((label,index)=><label key={label}><input type="checkbox" checked={days.includes(index)} onChange={()=>setDays(current=>current.includes(index)?current.filter(day=>day!==index):[...current,index].sort())}/><span>{label}</span></label>)}</fieldset><SubmitButtons close={close} label={template?"Save schedule":"Create schedule"} disabled={!days.length}/></ModalForm>}

function ModalForm({title,subtitle,wide,close,submit,children}:{title:string;subtitle?:string;wide?:boolean;close:()=>void;submit:()=>Promise<void>;children:React.ReactNode}){const {error,saving}=useContext(ActionContext);return <div className="modal-backdrop"><form className={`live-modal${wide?" wide-modal":""}`} onSubmit={e=>{e.preventDefault();void submit()}}><header><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button type="button" disabled={saving} onClick={close}><X/></button></header>{error&&<div className="live-alert error" role="alert">{error}</div>}<fieldset className="modal-fields" disabled={saving}>{children}</fieldset>{saving&&<p>Saving changes…</p>}</form></div>}
function SubmitButtons({close,label,disabled}:{close:()=>void;label:string;disabled?:boolean}){return <footer><button type="button" onClick={close}>Cancel</button><button className="live-primary" disabled={disabled}>{label}</button></footer>}

function AssignmentsView({data,action}:{data:Data;action:Action}){
 const [query,setQuery]=useState(""),[unassigned,setUnassigned]=useState(false),[selected,setSelected]=useState<Profile|null>(null);
 const frozen=data.events.some(e=>!e.closed_at);
 return <><div className="live-toolbar"><label><Search/><input aria-label="Search assignments" placeholder="Search name or email" value={query} onChange={e=>setQuery(e.target.value)}/></label><label><input type="checkbox" checked={unassigned} onChange={e=>setUnassigned(e.target.checked)}/>Unassigned only</label></div>
 {frozen&&<p className="inline-warning">Close the active room check before moving or removing residents.</p>}
 <p>Assign a residence room to any account, including your own Dean account. Checker responsibility is managed separately in Checker Coverage.</p>
 <section className="live-table"><table><thead><tr><th>Resident</th><th>Current room</th><th>Assignment</th></tr></thead><tbody>{data.profiles.filter(p=>(!unassigned||!data.assignments.some(a=>a.student_id===p.id))&&`${p.full_name} ${p.email}`.toLowerCase().includes(query.toLowerCase())).map(p=>{const a=data.assignments.find(a=>a.student_id===p.id),r=data.rooms.find(r=>r.id===a?.room_id),f=data.floors.find(f=>f.id===r?.floor_id);return <tr key={p.id}><td><strong>{p.full_name}{p.id===data.viewerId?" (You)":""}</strong><small>{p.email} · {p.role}</small></td><td>{r?`${f?.hall} · ${f?.label} · Room ${r.room_number}`:"Unassigned"}</td><td><button disabled={frozen} className="live-primary" onClick={()=>setSelected(p)}>{r?"Move resident":"Assign room"}</button>{r&&<button disabled={frozen} onClick={()=>confirm(`Remove ${p.full_name} from Room ${r.room_number}?`)&&void action({action:"remove_assignment",studentId:p.id})}>Remove assignment</button>}</td></tr>})}</tbody></table></section>
 {selected&&<AssignResidentModal profile={selected} data={data} action={action} close={()=>setSelected(null)}/>}</>;
}
function AssignResidentModal({profile,data,action,close}:{profile:Profile;data:Data;action:Action;close:()=>void}){
 const current=data.assignments.find(a=>a.student_id===profile.id)?.room_id;
 const [roomId,setRoomId]=useState(current||"");
 return <ModalForm title="Assign resident room" subtitle={profile.full_name} close={close} submit={async()=>{if(await action({action:"assign_student",studentId:profile.id,roomId},"Resident room saved"))close()}}>
 <label>Destination room<select required value={roomId} onChange={e=>setRoomId(e.target.value)}><option value="">Choose an available room</option>{data.rooms.filter(r=>r.active).map(r=>{const used=data.assignments.filter(a=>a.room_id===r.id).length,f=data.floors.find(f=>f.id===r.floor_id);return <option key={r.id} value={r.id} disabled={used>=r.capacity&&r.id!==current}>{f?.hall} · {f?.label} · Room {r.room_number} — {used}/{r.capacity} beds occupied</option>})}</select></label>
 <p>Moving a resident releases their previous bed. Full rooms cannot be selected.</p><SubmitButtons close={close} label="Save resident assignment" disabled={!roomId||roomId===current}/></ModalForm>;
}
function CoverageView({data,action,navigate}:{data:Data;action:Action;navigate:(view:View)=>void}){
 const [checker,setChecker]=useState<Profile|null>(null);
 const uncovered=data.rooms.filter(r=>r.active&&!r.checker_id);
 return <><div className="live-toolbar"><p>{uncovered.length} active rooms without a checker</p><button className="live-primary" onClick={()=>navigate("Users & Roles")}>Promote or manage checkers</button></div>
 {uncovered.length>0&&<p className="inline-warning">Uncovered: {uncovered.map(r=>{const f=data.floors.find(f=>f.id===r.floor_id);return `${f?.hall} / ${r.room_number}`}).join(", ")}</p>}
 <div className="live-room-grid">{data.profiles.filter(p=>p.role==="checker").map(p=>{const rooms=data.rooms.filter(r=>r.active&&r.checker_id===p.id);return <article key={p.id}><h3>{p.full_name}</h3><p>{p.email}</p><p>{rooms.length} rooms · {data.assignments.filter(a=>rooms.some(r=>r.id===a.room_id)).length} residents to check</p><p>{rooms.map(r=>r.room_number).join(", ")||"No coverage assigned"}</p><button className="live-primary" onClick={()=>setChecker(p)}>Assign checker rooms</button></article>})}</div>
 {!data.profiles.some(p=>p.role==="checker")&&<p>Promote a school account to Checker in Users &amp; Roles, then assign their rooms here.</p>}
 {checker&&<CheckerRoomsModal checker={checker} rooms={data.rooms} floors={data.floors} close={()=>setChecker(null)} action={action}/>}</>;
}
function OccupancyView({data,navigate}:{data:Data;navigate:(view:View)=>void}){
 return <><p>Live bed availability by residence floor. Inactive rooms are excluded.</p><div className="live-room-grid">{data.floors.map(f=>{const rooms=data.rooms.filter(r=>r.active&&r.floor_id===f.id),beds=rooms.reduce((n,r)=>n+r.capacity,0),used=data.assignments.filter(a=>rooms.some(r=>r.id===a.room_id)).length;return <article key={f.id}><h3>{f.hall} · {f.label}</h3><p>{used} / {beds} beds occupied</p><p>{beds-used} available beds · {rooms.filter(r=>!r.checker_id).length} rooms without coverage</p><button className="live-primary" onClick={()=>navigate("Room Assignments")}>Manage resident assignments</button><button onClick={()=>navigate("Checker Coverage")}>Manage coverage</button></article>})}</div>{!data.floors.length&&<button className="live-primary" onClick={()=>navigate("Rooms")}>Create your first floor and room</button>}</>;
}
