"use client";

import { useState } from "react";
import { BarChart3, BedDouble, Check, ClipboardCheck, DoorOpen, LayoutDashboard, LogOut, ScanLine, UserCog, Users } from "lucide-react";
import { QRCodeCanvas } from "qrcode.react";

type Role="student"|"checker"|"dean";

export function DemoPreview({role,close}:{role:Role;close:()=>void}){
 if(role==="student")return <StudentDemo close={close}/>;
 if(role==="checker")return <CheckerDemo close={close}/>;
 return <DeanDemo close={close}/>;
}

function DemoHeader({label,close}:{label:string;close:()=>void}){return <header className="demo-header"><div className="brand compact"><span className="crest">K</span><div><strong>Kingsway</strong><small>{label} demo</small></div></div><span className="demo-badge">DEMO MODE</span><button onClick={close}><LogOut/> Back to login</button></header>}

function StudentDemo({close}:{close:()=>void}){return <main className="demo-mobile"><DemoHeader label="Student" close={close}/><section className="demo-student-hero"><span>NIGHT ROOM CHECK</span><h1>Good evening, Olivia</h1><p>Show this rotating code to the checker in your assigned room.</p></section><section className="demo-qr-card"><div><span><i/> READY TO SCAN</span><b>Room N-214</b></div><QRCodeCanvas value="DEMO-STUDENT-KWC-10428-N214" size={230} fgColor="#073f35"/><h2>Olivia Bennett</h2><p>KWC-10428 · Grade 11</p><footer>Demo codes cannot submit attendance.</footer></section><section className="demo-room"><DoorOpen/><div><span>YOUR ASSIGNED ROOM</span><strong>North Hall · Room N-214</strong></div></section></main>}

function CheckerDemo({close}:{close:()=>void}){const[done,setDone]=useState(["Olivia Bennett"]);const students=["Olivia Bennett","Mateo Silva","Ethan Park","Amara Okafor"];return <main className="demo-mobile checker-demo"><DemoHeader label="Checker" close={close}/><section className="demo-check-head"><span>ROOM CHECK IN PROGRESS</span><h1>North Hall · Floor 2</h1><p>Night Check · 10:00 PM</p><b>{done.length}/4 verified</b></section><button className="demo-scan" onClick={()=>setDone(students)}><ScanLine/> Simulate QR scan</button><section className="demo-check-room"><header><DoorOpen/><strong>Rooms N-214 & N-216</strong></header>{students.map(name=><div key={name}><span className={done.includes(name)?"verified":""}>{done.includes(name)?<Check/>:name.split(" ").map(part=>part[0]).join("")}</span><div><strong>{name}</strong><small>{done.includes(name)?"Verified by QR":"Waiting for verification"}</small></div></div>)}</section></main>}

function DeanDemo({close}:{close:()=>void}){const[view,setView]=useState("Overview");const nav=[["Overview",LayoutDashboard],["Students",Users],["Users & Roles",UserCog],["Rooms",BedDouble],["Live check",ClipboardCheck],["Reports",BarChart3]] as const;return <main className="demo-dean"><aside><div className="brand"><span className="crest">K</span><div><strong>Kingsway</strong><small>Dean demo</small></div></div><nav>{nav.map(([name,Icon])=><button className={view===name?"active":""} key={name} onClick={()=>setView(name)}><Icon/>{name}</button>)}</nav><button className="demo-exit" onClick={close}><LogOut/> Back to login</button></aside><section><header><div><span>DEAN ADMINISTRATION · DEMO</span><h1>{view}</h1></div><span className="demo-badge">READ-ONLY PREVIEW</span></header>{view==="Overview"?<><div className="demo-metrics"><article><span>Active students</span><strong>98</strong></article><article><span>Assigned rooms</span><strong>48</strong></article><article><span>Tonight verified</span><strong>92%</strong></article><article><span>Photo reviews</span><strong>3</strong></article></div><section className="demo-panel"><div><span>LIVE ROOM CHECK</span><h2>Night Check · 10:00 PM</h2></div><div className="demo-progress"><span style={{width:"92%"}}/></div><p>90 of 98 students verified across 4 floors.</p></section></>:<DemoSection view={view}/>}</section></main>}

function DemoSection({view}:{view:string}){const copy:Record<string,[string,string,string[]]>={"Students":["Student directory","Manage profiles and room assignments.",["Olivia Bennett · N-214","Mateo Silva · N-214","Ethan Park · N-216"]],"Users & Roles":["Users and permissions","Promote students and assign Checker access.",["Daniel Morgan · Dean","Sarah Collins · Checker","Olivia Bennett · Student"]],"Rooms":["Residence rooms","Assign students and Checkers to specific rooms.",["N-214 · Sarah Collins","N-216 · Sarah Collins","S-108 · James Wilson"]],"Live check":["Night Check in progress","Monitor verification and photo exceptions.",["North Hall Floor 1 · 100%","North Hall Floor 2 · 92%","South Hall Floor 1 · 86%"]],"Reports":["Attendance reports","Review daily and weekly performance.",["Today · 92%","Last 7 days · 96.4%","Photo exceptions · 8"]]};const[itemTitle,description,items]=copy[view]??copy.Students;return <section className="demo-panel demo-list"><div><span>READ-ONLY DEMONSTRATION</span><h2>{itemTitle}</h2><p>{description}</p></div>{items.map(item=><article key={item}><Check/><strong>{item}</strong></article>)}</section>}
