"use client";

import { useCallback, useEffect, useState } from "react";
import { authFetch } from "@/lib/auth-fetch";

type Ticket={id:string;title:string;description:string;priority:string;status:string;resolution:string|null;created_at:string;rooms:{room_number:string};profiles:{full_name:string}|null};
export function ResidenceRequests({rooms,dean=false}:{rooms:{id:string;room_number:string}[];dean?:boolean}) {
 const[tickets,setTickets]=useState<Ticket[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[form,setForm]=useState({roomId:rooms[0]?.id??"",title:"",description:"",priority:"normal"});
 const load=useCallback(async()=>{try{const data=await authFetch("/api/residence/requests");setTickets(data.requests);setError("")}catch(e){setError(e instanceof Error?e.message:"Requests unavailable")}finally{setLoading(false)}},[]);
 useEffect(()=>{queueMicrotask(load)},[load]);
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);try{await authFetch("/api/residence/requests",{method:"POST",body:JSON.stringify(form)});setForm({...form,title:"",description:""});await load()}catch(e){setError(e instanceof Error?e.message:"Request failed")}finally{setBusy(false)}}
 async function update(ticket:Ticket,status:string){let resolution=ticket.resolution??"";if(status==="resolved"){const answer=prompt("Describe the resolution",resolution);if(answer===null)return;resolution=answer;}setBusy(true);try{await authFetch("/api/residence/requests",{method:"POST",body:JSON.stringify({action:"update",id:ticket.id,status,resolution})});await load()}catch(e){setError(e instanceof Error?e.message:"Update failed")}finally{setBusy(false)}}
 return <section className="live-panel residence-requests"><div className="live-panel-title"><div><span>RESIDENCE CARE</span><h2>{dean?"Maintenance requests":"Report a room issue"}</h2></div></div><p>For emergencies, contact residence staff immediately. This is not an emergency response service.</p>{error&&<div className="live-alert error" role="alert">{error}</div>}{rooms.length>0&&<form className="request-form" onSubmit={create}><label>Room<select required value={form.roomId} onChange={e=>setForm({...form,roomId:e.target.value})}><option value="" disabled>Select a room</option>{rooms.map(r=><option key={r.id} value={r.id}>Room {r.room_number}</option>)}</select></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="normal">Normal</option><option value="urgent">Urgent</option></select></label><label>Issue<input required minLength={3} maxLength={120} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Broken desk lamp"/></label><label>Description<textarea required minLength={10} maxLength={2000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="live-primary" disabled={busy}>{busy?"Saving…":"Submit request"}</button></form>}<h3>{dean?"Latest requests (up to 200)":"Your latest requests"}</h3>{loading?<p>Loading requests…</p>:tickets.length===0?<p>No maintenance requests.</p>:tickets.map(t=><article className="request-card" key={t.id}><header><strong>{t.title}</strong><span className={`role-pill ${t.priority==="urgent"?"dean":"student"}`}>{t.priority}</span></header><small>Room {t.rooms?.room_number} · {t.profiles?.full_name||"Resident"} · {new Date(t.created_at).toLocaleString()}</small><p>{t.description}</p>{t.resolution&&<p><strong>Resolution:</strong> {t.resolution}</p>}{dean?<label>Status<select disabled={busy} value={t.status} onChange={e=>void update(t,e.target.value)}><option value="open">Open</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option></select></label>:<span className="role-pill">{t.status.replaceAll("_"," ")}</span>}</article>)}</section>;
}
